/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainProfileRouteRouteImport } from './routes/_main/profile/route'
import { Route as MainProfileIndexRouteImport } from './routes/_main/profile/index'
import { Route as MainHotelsIndexRouteImport } from './routes/_main/hotels/index'
import { Route as MainFavouritesIndexRouteImport } from './routes/_main/favourites/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as MainProfileAccountIndexRouteImport } from './routes/_main/profile/account/index'
import { Route as MainHotelsHotelIdIndexRouteImport } from './routes/_main/hotels/$hotelId/index'
import { Route as ApiWebhooksStripeSplatRouteImport } from './routes/api/webhooks/stripe/$'
import { Route as ApiWebhooksClerkSplatRouteImport } from './routes/api/webhooks/clerk/$'
import { Route as MainHotelsHotelIdCheckoutIndexRouteImport } from './routes/_main/hotels/$hotelId/checkout/index'
import { Route as MainHotelsHotelIdCheckoutRoomIdIndexRouteImport } from './routes/_main/hotels/$hotelId/checkout/$roomId/index'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileRouteRoute = MainProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileIndexRoute = MainProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainProfileRouteRoute,
} as any)
const MainHotelsIndexRoute = MainHotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFavouritesIndexRoute = MainFavouritesIndexRouteImport.update({
  id: '/favourites/',
  path: '/favourites/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainProfileAccountIndexRoute = MainProfileAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => MainProfileRouteRoute,
} as any)
const MainHotelsHotelIdIndexRoute = MainHotelsHotelIdIndexRouteImport.update({
  id: '/hotels/$hotelId/',
  path: '/hotels/$hotelId/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiWebhooksStripeSplatRoute = ApiWebhooksStripeSplatRouteImport.update({
  id: '/api/webhooks/stripe/$',
  path: '/api/webhooks/stripe/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkSplatRoute = ApiWebhooksClerkSplatRouteImport.update({
  id: '/api/webhooks/clerk/$',
  path: '/api/webhooks/clerk/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainHotelsHotelIdCheckoutIndexRoute =
  MainHotelsHotelIdCheckoutIndexRouteImport.update({
    id: '/hotels/$hotelId/checkout/',
    path: '/hotels/$hotelId/checkout/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainHotelsHotelIdCheckoutRoomIdIndexRoute =
  MainHotelsHotelIdCheckoutRoomIdIndexRouteImport.update({
    id: '/hotels/$hotelId/checkout/$roomId/',
    path: '/hotels/$hotelId/checkout/$roomId/',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/profile': typeof MainProfileRouteRouteWithChildren
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/favourites/': typeof MainFavouritesIndexRoute
  '/hotels/': typeof MainHotelsIndexRoute
  '/profile/': typeof MainProfileIndexRoute
  '/api/webhooks/clerk/$': typeof ApiWebhooksClerkSplatRoute
  '/api/webhooks/stripe/$': typeof ApiWebhooksStripeSplatRoute
  '/hotels/$hotelId/': typeof MainHotelsHotelIdIndexRoute
  '/profile/account/': typeof MainProfileAccountIndexRoute
  '/hotels/$hotelId/checkout/': typeof MainHotelsHotelIdCheckoutIndexRoute
  '/hotels/$hotelId/checkout/$roomId/': typeof MainHotelsHotelIdCheckoutRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/favourites': typeof MainFavouritesIndexRoute
  '/hotels': typeof MainHotelsIndexRoute
  '/profile': typeof MainProfileIndexRoute
  '/api/webhooks/clerk/$': typeof ApiWebhooksClerkSplatRoute
  '/api/webhooks/stripe/$': typeof ApiWebhooksStripeSplatRoute
  '/hotels/$hotelId': typeof MainHotelsHotelIdIndexRoute
  '/profile/account': typeof MainProfileAccountIndexRoute
  '/hotels/$hotelId/checkout': typeof MainHotelsHotelIdCheckoutIndexRoute
  '/hotels/$hotelId/checkout/$roomId': typeof MainHotelsHotelIdCheckoutRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/profile': typeof MainProfileRouteRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_main/favourites/': typeof MainFavouritesIndexRoute
  '/_main/hotels/': typeof MainHotelsIndexRoute
  '/_main/profile/': typeof MainProfileIndexRoute
  '/api/webhooks/clerk/$': typeof ApiWebhooksClerkSplatRoute
  '/api/webhooks/stripe/$': typeof ApiWebhooksStripeSplatRoute
  '/_main/hotels/$hotelId/': typeof MainHotelsHotelIdIndexRoute
  '/_main/profile/account/': typeof MainProfileAccountIndexRoute
  '/_main/hotels/$hotelId/checkout/': typeof MainHotelsHotelIdCheckoutIndexRoute
  '/_main/hotels/$hotelId/checkout/$roomId/': typeof MainHotelsHotelIdCheckoutRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/forgot-password/'
    | '/sign-in/'
    | '/sign-up/'
    | '/favourites/'
    | '/hotels/'
    | '/profile/'
    | '/api/webhooks/clerk/$'
    | '/api/webhooks/stripe/$'
    | '/hotels/$hotelId/'
    | '/profile/account/'
    | '/hotels/$hotelId/checkout/'
    | '/hotels/$hotelId/checkout/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/favourites'
    | '/hotels'
    | '/profile'
    | '/api/webhooks/clerk/$'
    | '/api/webhooks/stripe/$'
    | '/hotels/$hotelId'
    | '/profile/account'
    | '/hotels/$hotelId/checkout'
    | '/hotels/$hotelId/checkout/$roomId'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_main/profile'
    | '/_main/'
    | '/_auth/forgot-password/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_main/favourites/'
    | '/_main/hotels/'
    | '/_main/profile/'
    | '/api/webhooks/clerk/$'
    | '/api/webhooks/stripe/$'
    | '/_main/hotels/$hotelId/'
    | '/_main/profile/account/'
    | '/_main/hotels/$hotelId/checkout/'
    | '/_main/hotels/$hotelId/checkout/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ApiWebhooksClerkSplatRoute: typeof ApiWebhooksClerkSplatRoute
  ApiWebhooksStripeSplatRoute: typeof ApiWebhooksStripeSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile/': {
      id: '/_main/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof MainProfileIndexRouteImport
      parentRoute: typeof MainProfileRouteRoute
    }
    '/_main/hotels/': {
      id: '/_main/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof MainHotelsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/favourites/': {
      id: '/_main/favourites/'
      path: '/favourites'
      fullPath: '/favourites/'
      preLoaderRoute: typeof MainFavouritesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/profile/account/': {
      id: '/_main/profile/account/'
      path: '/account'
      fullPath: '/profile/account/'
      preLoaderRoute: typeof MainProfileAccountIndexRouteImport
      parentRoute: typeof MainProfileRouteRoute
    }
    '/_main/hotels/$hotelId/': {
      id: '/_main/hotels/$hotelId/'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId/'
      preLoaderRoute: typeof MainHotelsHotelIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/webhooks/stripe/$': {
      id: '/api/webhooks/stripe/$'
      path: '/api/webhooks/stripe/$'
      fullPath: '/api/webhooks/stripe/$'
      preLoaderRoute: typeof ApiWebhooksStripeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk/$': {
      id: '/api/webhooks/clerk/$'
      path: '/api/webhooks/clerk/$'
      fullPath: '/api/webhooks/clerk/$'
      preLoaderRoute: typeof ApiWebhooksClerkSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/hotels/$hotelId/checkout/': {
      id: '/_main/hotels/$hotelId/checkout/'
      path: '/hotels/$hotelId/checkout'
      fullPath: '/hotels/$hotelId/checkout/'
      preLoaderRoute: typeof MainHotelsHotelIdCheckoutIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/hotels/$hotelId/checkout/$roomId/': {
      id: '/_main/hotels/$hotelId/checkout/$roomId/'
      path: '/hotels/$hotelId/checkout/$roomId'
      fullPath: '/hotels/$hotelId/checkout/$roomId/'
      preLoaderRoute: typeof MainHotelsHotelIdCheckoutRoomIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainProfileRouteRouteChildren {
  MainProfileIndexRoute: typeof MainProfileIndexRoute
  MainProfileAccountIndexRoute: typeof MainProfileAccountIndexRoute
}

const MainProfileRouteRouteChildren: MainProfileRouteRouteChildren = {
  MainProfileIndexRoute: MainProfileIndexRoute,
  MainProfileAccountIndexRoute: MainProfileAccountIndexRoute,
}

const MainProfileRouteRouteWithChildren =
  MainProfileRouteRoute._addFileChildren(MainProfileRouteRouteChildren)

interface MainRouteRouteChildren {
  MainProfileRouteRoute: typeof MainProfileRouteRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
  MainFavouritesIndexRoute: typeof MainFavouritesIndexRoute
  MainHotelsIndexRoute: typeof MainHotelsIndexRoute
  MainHotelsHotelIdIndexRoute: typeof MainHotelsHotelIdIndexRoute
  MainHotelsHotelIdCheckoutIndexRoute: typeof MainHotelsHotelIdCheckoutIndexRoute
  MainHotelsHotelIdCheckoutRoomIdIndexRoute: typeof MainHotelsHotelIdCheckoutRoomIdIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainProfileRouteRoute: MainProfileRouteRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
  MainFavouritesIndexRoute: MainFavouritesIndexRoute,
  MainHotelsIndexRoute: MainHotelsIndexRoute,
  MainHotelsHotelIdIndexRoute: MainHotelsHotelIdIndexRoute,
  MainHotelsHotelIdCheckoutIndexRoute: MainHotelsHotelIdCheckoutIndexRoute,
  MainHotelsHotelIdCheckoutRoomIdIndexRoute:
    MainHotelsHotelIdCheckoutRoomIdIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  ApiWebhooksClerkSplatRoute: ApiWebhooksClerkSplatRoute,
  ApiWebhooksStripeSplatRoute: ApiWebhooksStripeSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
